// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'FooterTwof': typeof import("../components/footer/twof.vue")['default'],
    'ModalSm': typeof import("../components/modal/sm.vue")['default'],
    'NavbarAside': typeof import("../components/navbar/aside.vue")['default'],
    'NavbarAuthtop': typeof import("../components/navbar/authtop.vue")['default'],
    'NavbarMega': typeof import("../components/navbar/mega.vue")['default'],
    'ProfileCustomer': typeof import("../components/profile/customer.vue")['default'],
    'SelectFilter': typeof import("../components/select/filter.vue")['default'],
    'TableAvatar': typeof import("../components/table/avatar.vue")['default'],
    'TableCustomer': typeof import("../components/table/customer.vue")['default'],
    'TableResultq': typeof import("../components/table/resultq.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyFooterTwof': typeof import("../components/footer/twof.vue")['default'],
    'LazyModalSm': typeof import("../components/modal/sm.vue")['default'],
    'LazyNavbarAside': typeof import("../components/navbar/aside.vue")['default'],
    'LazyNavbarAuthtop': typeof import("../components/navbar/authtop.vue")['default'],
    'LazyNavbarMega': typeof import("../components/navbar/mega.vue")['default'],
    'LazyProfileCustomer': typeof import("../components/profile/customer.vue")['default'],
    'LazySelectFilter': typeof import("../components/select/filter.vue")['default'],
    'LazyTableAvatar': typeof import("../components/table/avatar.vue")['default'],
    'LazyTableCustomer': typeof import("../components/table/customer.vue")['default'],
    'LazyTableResultq': typeof import("../components/table/resultq.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  }
}
export const FooterTwof: typeof import("../components/footer/twof.vue")['default']
export const ModalSm: typeof import("../components/modal/sm.vue")['default']
export const NavbarAside: typeof import("../components/navbar/aside.vue")['default']
export const NavbarAuthtop: typeof import("../components/navbar/authtop.vue")['default']
export const NavbarMega: typeof import("../components/navbar/mega.vue")['default']
export const ProfileCustomer: typeof import("../components/profile/customer.vue")['default']
export const SelectFilter: typeof import("../components/select/filter.vue")['default']
export const TableAvatar: typeof import("../components/table/avatar.vue")['default']
export const TableCustomer: typeof import("../components/table/customer.vue")['default']
export const TableResultq: typeof import("../components/table/resultq.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyFooterTwof: typeof import("../components/footer/twof.vue")['default']
export const LazyModalSm: typeof import("../components/modal/sm.vue")['default']
export const LazyNavbarAside: typeof import("../components/navbar/aside.vue")['default']
export const LazyNavbarAuthtop: typeof import("../components/navbar/authtop.vue")['default']
export const LazyNavbarMega: typeof import("../components/navbar/mega.vue")['default']
export const LazyProfileCustomer: typeof import("../components/profile/customer.vue")['default']
export const LazySelectFilter: typeof import("../components/select/filter.vue")['default']
export const LazyTableAvatar: typeof import("../components/table/avatar.vue")['default']
export const LazyTableCustomer: typeof import("../components/table/customer.vue")['default']
export const LazyTableResultq: typeof import("../components/table/resultq.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
